name: Update Booster Files

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Required to push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run booster split script
        run: python scripts/split_boosters.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add booster/ sealed_basic_data.json booster_index.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily booster data update"
            git push
          fi